In [2]:
import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import tensorflow as tf
import keras
import cv2
import pandas as pd


class Classifier:
    def __init__(self, model_path):
        self.model_path = model_path
        self.model = self.load_model()
        

    def load_model(self):
        model = keras.models.load_model(self.model_path)
        output1_layer = model.get_layer('output1')
        model1 = tf.keras.Model(inputs=model.input, outputs=output1_layer.output)
        model1.save('C:\\Users\\ChNa395\\Downloads\\doc_classification\\doc_classification_modified.keras')
        return model1

    def compile_model(self):
        self.model.compile(optimizer='adam',
                           loss='sparse_categorical_crossentropy',
                           metrics=['accuracy'])

    def prepare_image(self, img_path):
        img = cv2.imread(img_path, cv2.IMREAD_COLOR)
        img = cv2.resize(img, (448, 448))
        b,g,r = cv2.split(img)
        b = np.float64(b) / 127.5 - 1.0
        g = np.float64(g) / 127.5 - 1.0
        r = np.float64(r) / 127.5 - 1.0
        img_float = cv2.merge([b, g, r])
        img_float = np.expand_dims(img_float, axis=0)
        return img_float
    
    def predict_image(self, image_path):
        img_array = self.prepare_image(image_path)
        predictions = self.model.predict(img_array)
        print(predictions)
        return predictions

# model = tf.keras.models.load_model('C:\\Users\\ChNa395\\Downloads\\doc_classification\\doc_classification.h5')
# model.compile(optimizer='adam',
#               loss='sparse_categorical_crossentropy',
#               metrics=['accuracy'])

def get_classfied_label(index):
    if (index == 0):
        return "Card"
    elif (index == 1):
        return "Document"
    elif (index == 2):
        return "Photo"
    elif (index == 3):
        return "Receipt"
    else:
        return "Mixed"

def get_label(results):
    for i, pred in enumerate(results):
        max_index = -1
        max_index = np.argmax(pred)
        max_value = pred[max_index]
        if max_value > 0.85:
            return get_classfied_label(max_index)
        else:
            return "Mixed"


if __name__ == "__main__":
    input_dir = 'C:\\Users\\ChNa395\\python\\BatchRun\\Dump\\AllTargetsDump\\DeskewedTargets'
    csv_file = 'C:\\Users\\ChNa395\\python\\outputlist.csv'

    data_frame = pd.read_csv(csv_file)
    label_to_int_mapping = {'Card': 0, 'Document': 1, 'Photo':2, 'Receipt': 3, 'Mixed': 4}
    data_frame['labelInt'] = data_frame['Label'].map(label_to_int_mapping)
    data_frame['predicted_label'] = ''
    data_frame['predicted_label_int'] = -1
    for image in os.listdir(input_dir):
        image_path = os.path.join(input_dir, image)
        model_path = 'C:\\Users\\ChNa395\\Downloads\\doc_classification\\doc_classification.h5'
        classifierObj = Classifier(model_path)
        classifierObj.compile_model()
        predicted_output = get_label(classifierObj.predict_image(image_path))
        print(predicted_output)
        predicted_label_int = label_to_int_mapping[predicted_output]
        file_name = image.split('.')[0]
        file_name = file_name.strip()
        print(file_name)
        
        # data_frame.loc[data_frame['Filename'] == file_name, 'label_int'] = data_frame.loc[data_frame['Filename'] == file_name, 'labelInt']
        data_frame.loc[data_frame['Filename'] == file_name, 'predicted_label'] = predicted_output
        data_frame.loc[data_frame['Filename'] == file_name, 'predicted_label_int'] = predicted_label_int

    data_frame.to_csv('C:\\Users\\ChNa395\\python\\outputlist_modified.csv', index=False)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.0393244e-04 1.3981194e-03 1.3057671e-03 9.9545538e-01 9.3671598e-04]]
Receipt
CHYPRCE098_0315_162636_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.965467e-01 8.260735e-04 9.979270e-04 7.847189e-04 8.446219e-04]]
Card
CHYPRCE098_0315_162652_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 954ms/step
[[9.9485695e-01 1.3387143e-03 1.6356654e-03 1.2922891e-03 8.7631389e-04]]
Card
CHYPRCE098_0315_162744_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.19624373 0.0263964  0.7569555  0.01277781 0.00762662]]
Mixed
CHYPRCE098_0315_162816_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[3.7582931e-03 1.1170361e-03 8.9646195e-04 9.9357659e-01 6.5163296e-04]]
Receipt
CHYPRCE098_0315_162904_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9521482e-01 9.2806644e-04 1.4245404e-03 1.3253172e-03 1.1071996e-03]]
Card
CHYPRCE098_0315_162933_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9455053e-01 9.8577095e-04 1.9722753e-03 1.4118518e-03 1.0796179e-03]]
Card
CHYPRCE098_0315_163021_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9579465e-01 1.1261689e-03 1.3957224e-03 8.4759860e-04 8.3585602e-04]]
Card
CHYPRCE098_0315_163039_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9679166e-01 1.0174995e-03 7.3443557e-04 8.3486276e-04 6.2148244e-04]]
Card
CHYPRCE098_0315_163133_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9566537e-01 1.1458638e-03 9.9228357e-04 1.1149364e-03 1.0815634e-03]]
Card
CHYPRCE098_0315_163149_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9557626e-01 1.0279695e-03 1.1468146e-03 9.4362517e-04 1.3053983e-03]]
Card
CHYPRCE098_0315_163307_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.993743   0.0024263  0.00125437 0.00107741 0.00149897]]
Card
CHYPRCE098_0315_163324_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.99314886 0.00155372 0.00264365 0.00138103 0.0012728 ]]
Card
CHYPRCE098_0315_163417_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9613613e-01 7.6700374e-04 9.5570256e-04 1.0689941e-03 1.0721867e-03]]
Card
CHYPRCE098_0315_163432_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.99121046 0.00217675 0.00171964 0.00284789 0.00204541]]
Card
CHYPRCE098_0315_163538_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9562764e-01 9.1057509e-04 1.2200505e-03 1.0789464e-03 1.1627749e-03]]
Card
CHYPRCE098_0315_163554_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9610281e-01 9.8710996e-04 8.6737773e-04 1.1995926e-03 8.4303605e-04]]
Card
CHYPRCE098_0315_163703_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9592316e-01 8.6570746e-04 8.8215334e-04 1.2981083e-03 1.0308963e-03]]
Card
CHYPRCE098_0315_163720_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9635565e-01 7.4245548e-04 1.2401721e-03 7.3545030e-04 9.2629914e-04]]
Card
CHYPRCE098_0315_163817_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9920082  0.00221249 0.00241197 0.00161723 0.00175013]]
Card
CHYPRCE098_0315_163832_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.994576   0.00141301 0.00152684 0.00125952 0.00122469]]
Card
CHYPRCE098_0315_163919_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9654061e-01 7.5523613e-04 1.1594155e-03 6.9145422e-04 8.5320236e-04]]
Card
CHYPRCE098_0315_163934_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9934542  0.00122671 0.00282753 0.0013341  0.00115754]]
Card
CHYPRCE098_0315_164022_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9582821e-01 1.3034520e-03 1.0273715e-03 1.0041497e-03 8.3674234e-04]]
Card
CHYPRCE098_0315_164039_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9680638e-01 7.4520311e-04 7.1707251e-04 1.1239970e-03 6.0735276e-04]]
Card
CHYPRCE098_0315_164130_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.967339e-01 8.885181e-04 9.584394e-04 8.791025e-04 5.401298e-04]]
Card
CHYPRCE098_0315_164148_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[5.4706400e-03 9.1809762e-04 1.3269073e-03 9.9098301e-01 1.3012959e-03]]
Receipt
CHYPRCE098_0315_164234_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9656016e-01 9.5864071e-04 6.9685024e-04 1.1273653e-03 6.5692572e-04]]
Card
CHYPRCE098_0315_164255_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00900919 0.00103602 0.0011302  0.98737514 0.00144942]]
Receipt
CHYPRCE098_0315_164353_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[8.6893258e-04 8.5365423e-04 1.1182433e-03 9.9630702e-01 8.5212186e-04]]
Receipt
CHYPRCE098_0315_164411_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9938962  0.00141359 0.00216673 0.00142303 0.00110058]]
Card
CHYPRCE098_0315_164508_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[3.0800872e-03 1.2621321e-03 1.1463994e-03 9.9362367e-01 8.8779081e-04]]
Receipt
CHYPRCE098_0315_164529_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00163965 0.00107804 0.00104952 0.995161   0.00107179]]
Receipt
CHYPRCE098_0315_164633_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9952933  0.00109628 0.0012688  0.00131004 0.0010315 ]]
Card
CHYPRCE098_0315_164656_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9826068e-01 2.4556986e-04 5.4995593e-04 5.7775440e-04 3.6602508e-04]]
Card
CHYPRCE098_0315_164811_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9671859e-01 6.1796780e-04 1.0109002e-03 9.1544969e-04 7.3697628e-04]]
Card
CHYPRCE098_0315_164833_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9827072  0.00392419 0.00400424 0.00285009 0.00651427]]
Card
CHYPRCE098_0315_164923_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00237753 0.0019298  0.00127606 0.99302095 0.00139569]]
Receipt
CHYPRCE098_0315_164942_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00172566 0.00117082 0.00126332 0.99473804 0.0011022 ]]
Receipt
CHYPRCE098_0315_165029_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[3.9390805e-03 8.8245311e-04 1.2160242e-03 9.9269837e-01 1.2640775e-03]]
Receipt
CHYPRCE098_0315_165044_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00146599 0.00160379 0.00370816 0.9922293  0.00099279]]
Receipt
CHYPRCE098_0315_165135_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9617946e-01 7.0033612e-04 1.1965312e-03 1.0540632e-03 8.6969096e-04]]
Card
CHYPRCE098_0315_165200_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9721259e-01 7.2205329e-04 7.7386142e-04 6.7888841e-04 6.1259704e-04]]
Card
CHYPRCE098_0315_165250_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00579044 0.00200736 0.00398026 0.9860136  0.00220834]]
Receipt
CHYPRCE098_0315_165306_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00384824 0.00177356 0.00165296 0.99100906 0.00171617]]
Receipt
CHYPRCE098_0315_165356_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9732012e-01 4.6154018e-04 8.2749000e-04 8.2458905e-04 5.6623714e-04]]
Card
CHYPRCE098_0315_165413_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9513841e-01 1.1871808e-03 1.4198936e-03 1.3191819e-03 9.3531993e-04]]
Card
CHYPRCE098_0315_165502_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.2169785  0.01553724 0.01531471 0.53205764 0.22011182]]
Mixed
CHYPRCE098_0315_165520_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00222639 0.00102875 0.00150039 0.99364835 0.00159614]]
Receipt
CHYPRCE098_0315_165607_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9766529e-01 2.0439351e-04 4.8772348e-04 1.0844937e-03 5.5816484e-04]]
Card
CHYPRCE098_0315_165627_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00178902 0.00124651 0.00278184 0.9927752  0.00140742]]
Receipt
CHYPRCE098_0315_165714_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.4102509e-04 1.1976971e-03 1.4077171e-03 9.9521011e-01 1.2435281e-03]]
Receipt
CHYPRCE098_0315_165731_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00480544 0.00136221 0.00202705 0.9906579  0.00114733]]
Receipt
CHYPRCE098_0315_165819_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9695659e-01 6.1923871e-04 7.9600967e-04 8.2101423e-04 8.0712122e-04]]
Card
CHYPRCE098_0315_165835_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.01013837 0.00317084 0.0047035  0.98034406 0.00164323]]
Receipt
CHYPRCE098_0315_165920_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9532557e-01 9.8243251e-04 1.3580492e-03 1.3469084e-03 9.8690193e-04]]
Card
CHYPRCE098_0315_165937_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9579829e-01 1.1981055e-03 1.3272803e-03 8.8021765e-04 7.9611561e-04]]
Card
CHYPRCE098_0315_170027_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9819999  0.00222212 0.00411899 0.00826026 0.00339885]]
Card
CHYPRCE098_0315_170043_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[4.6760900e-04 6.7426817e-04 6.2491931e-04 9.9739611e-01 8.3703257e-04]]
Receipt
CHYPRCE098_0315_170133_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9949692  0.00108739 0.00148766 0.00112815 0.00132769]]
Card
CHYPRCE098_0315_170148_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[8.1572670e-04 9.5110125e-04 1.0405724e-03 9.9633551e-01 8.5710239e-04]]
Receipt
CHYPRCE098_0315_170233_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[5.6236383e-04 8.7654754e-04 7.3756033e-04 9.9725598e-01 5.6755770e-04]]
Receipt
CHYPRCE098_0315_170248_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9263966e-01 7.9088099e-04 1.5753692e-03 3.3590330e-03 1.6351156e-03]]
Card
CHYPRCE098_0315_170333_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9948539  0.00117625 0.0012485  0.00152328 0.00119812]]
Card
CHYPRCE098_0315_170351_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[8.1093272e-04 9.1748475e-04 9.9482958e-04 9.9637967e-01 8.9718984e-04]]
Receipt
CHYPRCE098_0315_170444_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[5.8406225e-04 8.7909849e-04 1.4895905e-03 9.9620289e-01 8.4430882e-04]]
Receipt
CHYPRCE098_0315_170500_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9436474e-01 7.2573166e-04 1.6440722e-03 1.4401665e-03 1.8252617e-03]]
Card
CHYPRCE098_0315_170612_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9561876e-01 9.2492398e-04 1.0553906e-03 1.3077967e-03 1.0930707e-03]]
Card
CHYPRCE098_0315_170630_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9936069  0.00124522 0.00190119 0.00176817 0.00147841]]
Card
CHYPRCE098_0315_170722_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9765961  0.00471418 0.00294942 0.00962899 0.00611134]]
Card
CHYPRCE098_0315_170737_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[1.0835194e-03 8.1896473e-04 1.1446254e-03 9.9614847e-01 8.0432522e-04]]
Receipt
CHYPRCE098_0315_170831_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9711442e-01 7.4880139e-04 8.5260544e-04 8.0342003e-04 4.8074251e-04]]
Card
CHYPRCE098_0315_170850_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9609464e-01 8.6178159e-04 1.2329717e-03 9.6761086e-04 8.4310997e-04]]
Card
CHYPRCE098_0315_170937_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.25773257 0.00498533 0.00348393 0.7287001  0.0050981 ]]
Mixed
CHYPRCE098_0315_170952_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.99297696 0.00129275 0.0022283  0.00199074 0.00151109]]
Card
CHYPRCE098_0315_171037_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9058888  0.00587805 0.00643526 0.07464567 0.00715225]]
Card
CHYPRCE098_0315_171053_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.981881   0.00246931 0.00174995 0.01045225 0.00344743]]
Card
CHYPRCE098_0315_171139_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.01095891 0.00190803 0.002182   0.983547   0.00140412]]
Receipt
CHYPRCE098_0315_171244_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[8.6335553e-04 1.0259080e-03 8.9276844e-04 9.9654913e-01 6.6873914e-04]]
Receipt
CHYPRCE098_0315_171304_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[3.1835798e-02 1.3564168e-03 8.8198140e-04 9.6493942e-01 9.8636735e-04]]
Receipt
CHYPRCE098_0315_171352_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.0346631  0.00258033 0.02019386 0.91745955 0.02510317]]
Receipt
CHYPRCE098_0315_171425_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9705243e-01 6.8456249e-04 6.0733815e-04 7.9481892e-04 8.6071854e-04]]
Card
CHYPRCE098_0315_171509_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[8.8882085e-04 1.0454368e-03 9.6147170e-04 9.9645424e-01 6.5007532e-04]]
Receipt
CHYPRCE098_0315_171530_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.99285525 0.00225049 0.00209527 0.00154844 0.00125057]]
Card
CHYPRCE098_0315_171634_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00437898 0.00101801 0.0011033  0.9916299  0.00186979]]
Receipt
CHYPRCE098_0315_171721_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9858263  0.00339835 0.00168165 0.00725769 0.00183589]]
Card
CHYPRCE098_0315_171740_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9676102e-01 7.2169228e-04 1.0364777e-03 8.4116985e-04 6.3957938e-04]]
Card
CHYPRCE098_0315_171825_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9728429e-01 6.2789064e-04 7.4968353e-04 7.3341379e-04 6.0470204e-04]]
Card
CHYPRCE098_0315_171843_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.92060745 0.00848979 0.01314266 0.04747931 0.0102809 ]]
Card
CHYPRCE098_0315_171929_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[1.0257451e-03 1.0912908e-03 9.0000685e-04 9.9597460e-01 1.0084535e-03]]
Receipt
CHYPRCE098_0315_171948_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.99384034 0.0014877  0.00118863 0.00190047 0.00158281]]
Card
CHYPRCE098_0315_172033_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[4.6306770e-04 6.0167123e-04 1.3575607e-03 9.9698120e-01 5.9649587e-04]]
Receipt
CHYPRCE098_0315_172049_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9824928  0.00310205 0.00098408 0.01006559 0.00335551]]
Card
CHYPRCE098_0315_172134_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9518824e-01 1.4501282e-03 1.3165200e-03 1.1684125e-03 8.7670435e-04]]
Card
CHYPRCE098_0315_172151_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9568546e-01 9.7914203e-04 1.7610124e-03 8.1378501e-04 7.6075445e-04]]
Card
CHYPRCE098_0315_172243_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[7.5000647e-04 1.1647675e-03 1.1578207e-03 9.9581784e-01 1.1095998e-03]]
Receipt
CHYPRCE098_0315_172303_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9524397e-01 8.7651605e-04 1.6158709e-03 1.3135542e-03 9.5006102e-04]]
Card
CHYPRCE098_0315_172348_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9550432e-01 7.0022471e-04 8.1440865e-04 1.6211276e-03 1.3598491e-03]]
Card
CHYPRCE098_0315_172409_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[7.6426740e-04 9.6252048e-04 1.1199093e-03 9.9580318e-01 1.3501210e-03]]
Receipt
CHYPRCE098_0315_172457_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9647444e-01 7.2371517e-04 9.7967021e-04 9.3996513e-04 8.8223018e-04]]
Card
CHYPRCE098_0315_172513_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9535781e-01 1.0383197e-03 1.4284342e-03 1.2602540e-03 9.1514591e-04]]
Card
CHYPRCE098_0315_172600_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.99352646 0.00161289 0.00226774 0.00137836 0.00121457]]
Card
CHYPRCE098_0315_172621_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9944956  0.0010702  0.00185087 0.00129926 0.00128412]]
Card
CHYPRCE098_0315_172707_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9933876  0.00150156 0.00203861 0.00157527 0.00149692]]
Card
CHYPRCE098_0315_172722_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.97562826 0.00318754 0.00349928 0.01389703 0.00378785]]
Card
CHYPRCE098_0315_172807_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9774337e-01 5.3298188e-04 6.5589329e-04 6.6625327e-04 4.0152034e-04]]
Card
CHYPRCE098_0315_172826_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.09810859 0.00191772 0.00512743 0.8891663  0.00568001]]
Receipt
CHYPRCE098_0315_172910_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9396485e-01 8.8010228e-04 7.9896447e-04 2.8112358e-03 1.5449193e-03]]
Card
CHYPRCE098_0315_172928_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.7384732  0.01466758 0.02117786 0.20703237 0.01864898]]
Mixed
CHYPRCE098_0315_173024_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9651968e-01 3.6918256e-04 1.1788743e-03 1.3607027e-03 5.7156989e-04]]
Card
CHYPRCE098_0315_173042_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00188308 0.0018042  0.00204934 0.99241567 0.00184768]]
Receipt
CHYPRCE098_0315_173129_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.99516535 0.00116419 0.00126022 0.00119462 0.00121562]]
Card
CHYPRCE098_0315_173145_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9536222e-01 9.5108279e-04 1.4435641e-03 1.2754069e-03 9.6779561e-04]]
Card
CHYPRCE098_0315_173252_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9656397e-01 5.6409772e-04 1.0994915e-03 9.7734272e-04 7.9511094e-04]]
Card
CHYPRCE098_0315_173315_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[7.8226964e-04 1.2325493e-03 9.0765639e-04 9.9646407e-01 6.1353174e-04]]
Receipt
CHYPRCE098_0315_173438_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9748528e-01 5.2208418e-04 7.7648443e-04 8.0132450e-04 4.1481436e-04]]
Card
CHYPRCE098_0315_173459_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.99456006 0.00134585 0.00164177 0.0014181  0.00103421]]
Card
CHYPRCE098_0315_173545_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99199295 0.00235697 0.00192981 0.00204106 0.00167926]]
Card
CHYPRCE098_0315_173603_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00712868 0.00198694 0.00145319 0.9882488  0.00118235]]
Receipt
CHYPRCE098_0315_173649_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9470641  0.00176599 0.00368255 0.04571604 0.00177138]]
Card
CHYPRCE098_0315_173704_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.00109661 0.00122302 0.00146054 0.99478406 0.00143581]]
Receipt
CHYPRCE098_0315_173859_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.3453930e-04 1.1139106e-03 1.1929092e-03 9.9544829e-01 1.3103384e-03]]
Receipt
CHYPRCE098_0315_173929_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9589396e-01 1.0042242e-03 1.3826122e-03 1.0082382e-03 7.1097247e-04]]
Card
CHYPRCE098_0315_174014_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9625248e-01 1.0031468e-03 1.0309570e-03 1.0631699e-03 6.5021619e-04]]
Card
CHYPRCE098_0315_174030_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.994672   0.00139833 0.00161806 0.00121599 0.00109564]]
Card
CHYPRCE098_0315_174114_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9489707e-01 1.0423522e-03 2.0531840e-03 1.1777238e-03 8.2959485e-04]]
Card
CHYPRCE098_0315_174130_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.03419492 0.00192903 0.00629313 0.9554579  0.00212505]]
Receipt
CHYPRCE098_0315_174434_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[8.0583093e-04 8.0150057e-04 1.2729403e-03 9.9629396e-01 8.2585891e-04]]
Receipt
CHYPRCE098_0315_174450_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9647754e-01 6.8625459e-04 1.0381246e-03 1.0028309e-03 7.9524599e-04]]
Card
CHYPRCE098_0315_174535_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9689269e-01 7.8088767e-04 9.9631806e-04 6.5990351e-04 6.7017117e-04]]
Card
CHYPRCE098_0315_174551_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9593437e-01 9.6085324e-04 8.9334458e-04 1.0985340e-03 1.1128418e-03]]
Card
CHYPRCE098_0315_174636_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.6845831e-04 1.7658544e-03 8.8377472e-04 9.9514318e-01 1.2388222e-03]]
Receipt
CHYPRCE098_0315_174651_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.15828075 0.00654998 0.014154   0.8091672  0.01184808]]
Mixed
CHYPRCE098_0315_174755_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9616724e-01 8.0267905e-04 1.0009934e-03 8.9250680e-04 1.1365291e-03]]
Card
CHYPRCE098_0315_174812_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9852188  0.00348981 0.0055561  0.00260332 0.00313201]]
Card
CHYPRCE098_0315_174855_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9700075e-01 7.3344511e-04 4.8178365e-04 1.2607778e-03 5.2318320e-04]]
Card
CHYPRCE098_0315_174916_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.9591172e-01 1.5563791e-03 6.2325888e-04 9.6145330e-04 9.4715599e-04]]
Card
CHYPRCE098_0315_175006_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[9.973398e-01 6.803040e-04 5.473522e-04 6.187968e-04 8.137515e-04]]
Card
CHYPRCE098_0326_115021_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99060905 0.00203253 0.00262984 0.00234642 0.00238214]]
Card
CHYPRCE098_0326_115150_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[0.9934729  0.00183528 0.00129391 0.00156452 0.00183339]]
Card
CHYPRCE098_0326_115219_300C_FB-mod_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9926985  0.00184581 0.00147318 0.0016363  0.00234618]]
Card
CHYPRCE098_0326_115219_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
[[0.98777467 0.00213437 0.00424741 0.0019264  0.00391709]]
Card
CHYPRCE098_0326_115317_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step
[[9.9600369e-01 1.0387180e-03 1.1213282e-03 8.1900740e-04 1.0172838e-03]]
Card
CHYPRCE098_0326_115337_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[0.99196637 0.00220077 0.00162074 0.00162895 0.00258319]]
Card
CHYPRCE098_0326_115426_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[0.00330111 0.99184155 0.00117863 0.00143481 0.00224393]]
Document
CHYPRCE098_0326_115444_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99208283 0.00212285 0.00235831 0.00177089 0.00166501]]
Card
CHYPRCE098_0326_115543_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[0.95648336 0.02240776 0.01548155 0.00368184 0.00194547]]
Card
CHYPRCE098_0326_115543_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[9.9691099e-01 7.2370499e-04 9.4961439e-04 5.9777923e-04 8.1782899e-04]]
Card
CHYPRCE098_0326_115739_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[9.9611026e-01 1.0326533e-03 9.0356538e-04 8.1164797e-04 1.1418554e-03]]
Card
CHYPRCE098_0326_115829_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.98036236 0.00493279 0.00274353 0.00265212 0.00930925]]
Card
CHYPRCE098_0326_115854_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9637622e-01 7.7500229e-04 8.5629831e-04 9.3965384e-04 1.0528688e-03]]
Card
CHYPRCE098_0326_115951_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9660647e-01 7.3011749e-04 1.1940871e-03 7.9485372e-04 6.7440677e-04]]
Card
CHYPRCE098_0326_120228_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9916597  0.00203839 0.00243474 0.00192982 0.00193732]]
Card
CHYPRCE098_0326_120315_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9696726e-01 8.7765325e-04 5.6880416e-04 8.7947689e-04 7.0673320e-04]]
Card
CHYPRCE098_0326_120337_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9417454e-01 2.4971720e-03 1.1599297e-03 1.3454305e-03 8.2297856e-04]]
Card
CHYPRCE098_0326_120429_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9617970e-01 7.3603640e-04 9.9090906e-04 7.6502323e-04 1.3283656e-03]]
Card
CHYPRCE098_0326_120450_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.36842665 0.6061341  0.01153652 0.00609775 0.00780502]]
Mixed
CHYPRCE098_0326_120549_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9660945e-01 8.4183714e-04 9.7482221e-04 8.5209194e-04 7.2185439e-04]]
Card
CHYPRCE098_0326_120627_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9798632e-01 2.7983313e-04 7.8055722e-04 5.5828638e-04 3.9496273e-04]]
Card
CHYPRCE098_0326_120722_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9934324  0.00185576 0.00170745 0.0016     0.0014043 ]]
Card
CHYPRCE098_0326_120859_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9691451e-01 7.4894330e-04 9.7539497e-04 8.1706361e-04 5.4408115e-04]]
Card
CHYPRCE098_0326_121008_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.3587715  0.01534221 0.34931934 0.2587208  0.01784613]]
Mixed
CHYPRCE098_0326_121054_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9865238  0.00298297 0.00447389 0.00264185 0.00337758]]
Card
CHYPRCE098_0326_121227_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9616301e-01 1.2254685e-03 8.0411683e-04 9.4960345e-04 8.5783628e-04]]
Card
CHYPRCE098_0326_121348_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9946694  0.0018496  0.00103144 0.0011473  0.00130218]]
Card
CHYPRCE098_0326_121449_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.85213339e-01 8.99587409e-04 1.11247385e-02 8.29145079e-04
  1.93320354e-03]]
Card
CHYPRCE098_0326_122322_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9585152e-01 1.1361743e-03 1.0079904e-03 1.0380300e-03 9.6618442e-04]]
Card
CHYPRCE098_0326_122811_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.6426745e-04 9.9738389e-01 1.7457034e-03 4.9571885e-04 2.1046822e-04]]
Document
CHYPRCE098_0402_105513_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.6206967e-03 9.9588674e-01 6.9440302e-04 1.4514027e-03 3.4673576e-04]]
Document
CHYPRCE098_0402_105513_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99111265 0.00235468 0.00229977 0.00176769 0.0024652 ]]
Card
CHYPRCE098_0402_105654_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.32242104 0.64434993 0.0145275  0.00853977 0.01016174]]
Mixed
CHYPRCE098_0402_105759_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[8.3886355e-04 9.9679774e-01 9.4758783e-04 7.5541087e-04 6.6047022e-04]]
Document
CHYPRCE098_0402_105759_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.3473347e-03 9.9680579e-01 6.8671379e-04 7.1105768e-04 4.4910255e-04]]
Document
CHYPRCE098_0402_105759_300C_FB_2


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9595612e-01 9.1765204e-04 8.9863292e-04 1.0816162e-03 1.1459754e-03]]
Card
CHYPRCE098_0402_105914_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9678481e-01 4.3492779e-04 1.2282575e-03 5.4139562e-04 1.0105713e-03]]
Card
CHYPRCE098_0402_105931_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9425215e-01 1.5659280e-03 1.9000007e-03 1.4481613e-03 8.3375617e-04]]
Card
CHYPRCE098_0402_110126_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9284172  0.05227894 0.0089456  0.00604071 0.0043175 ]]
Card
CHYPRCE098_0402_110148_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9926764  0.00200414 0.00221162 0.00153188 0.00157605]]
Card
CHYPRCE098_0402_110243_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.98668355 0.00741068 0.0012067  0.00303257 0.00166648]]
Card
CHYPRCE098_0402_110259_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.03654875 0.9004654  0.00801191 0.00449064 0.05048327]]
Document
CHYPRCE098_0402_110443_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.01660829 0.97550905 0.00338514 0.00210838 0.00238917]]
Document
CHYPRCE098_0402_110443_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.02326006 0.5350604  0.00899247 0.02395055 0.4087365 ]]
Mixed
CHYPRCE098_0402_110443_300C_FB_2


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00153768 0.99493474 0.00124675 0.00111781 0.001163  ]]
Document
CHYPRCE098_0402_110443_300C_FB_3


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.5457706e-04 9.9477851e-01 1.4330078e-03 1.4738351e-03 1.3601463e-03]]
Document
CHYPRCE098_0402_110530_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[4.9611967e-04 9.9567944e-01 1.2935961e-03 1.1572095e-03 1.3736319e-03]]
Document
CHYPRCE098_0402_110530_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00132232 0.99390256 0.00168159 0.00178711 0.00130648]]
Document
CHYPRCE098_0402_110530_300C_FB_2


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.1067246e-03 9.9600190e-01 9.0846268e-04 1.0090104e-03 9.7389729e-04]]
Document
CHYPRCE098_0402_110711_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00143856 0.00173651 0.9937982  0.00150669 0.00152003]]
Photo
CHYPRCE098_0402_110711_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[5.0703977e-04 9.9597090e-01 1.4577603e-03 1.0978888e-03 9.6639886e-04]]
Document
CHYPRCE098_0402_110711_300C_FB_2


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.7616879  0.00881192 0.01610919 0.01121741 0.20217356]]
Mixed
CHYPRCE098_0402_110711_300C_FB_3


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00371112 0.00167228 0.01675581 0.97461957 0.00324125]]
Receipt
CHYPRCE098_0402_110754_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[8.9581078e-04 9.9445349e-01 1.8290684e-03 1.4292243e-03 1.3923593e-03]]
Document
CHYPRCE098_0402_110754_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9620088  0.00990429 0.00949949 0.00489676 0.01369076]]
Card
CHYPRCE098_0402_110754_300C_FB_2


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.04255005 0.93889827 0.00933197 0.00493809 0.00428165]]
Document
CHYPRCE098_0402_110754_300C_FB_3


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00302124 0.00137275 0.00186685 0.00153845 0.9922008 ]]
Mixed
CHYPRCE098_0402_110754_300C_FB_4


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.1502061e-03 1.1074211e-03 9.9564362e-01 9.5970515e-04 1.1391189e-03]]
Photo
CHYPRCE098_0402_110919_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.01188566 0.03439584 0.9372439  0.00850603 0.00796871]]
Photo
CHYPRCE098_0402_110919_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[2.8747262e-04 9.9550194e-01 2.0609107e-03 1.0540503e-03 1.0956740e-03]]
Document
CHYPRCE098_0402_110919_300C_FB_2


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[5.1498075e-04 9.9335080e-01 1.1420787e-03 1.4839921e-03 3.5080994e-03]]
Document
CHYPRCE098_0402_110919_300C_FB_3


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.0020371e-03 9.9595648e-01 8.8847766e-04 1.0355720e-03 1.1173995e-03]]
Document
CHYPRCE098_0402_111011_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.2741198e-03 9.8843819e-01 9.7785308e-04 1.9111614e-03 7.3985988e-03]]
Document
CHYPRCE098_0402_111011_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.6534071e-03 9.7343147e-01 2.3138158e-02 1.4381973e-03 3.3878992e-04]]
Document
CHYPRCE098_0402_111011_300C_FB_2


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.96992469e-01 9.09808659e-05 1.06307154e-04 8.82665772e-05
  2.72203446e-03]]
Card
CHYPRCE098_0402_111133_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00151192 0.9949497  0.00111764 0.00123361 0.00118716]]
Document
CHYPRCE098_0402_111133_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9630332e-01 7.0536323e-04 8.4103219e-04 1.3084632e-03 8.4181898e-04]]
Card
CHYPRCE098_0402_111206_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9688977e-01 6.9616752e-04 8.3544553e-04 7.2320801e-04 8.5541548e-04]]
Card
CHYPRCE098_0402_111206_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[0.00105568 0.99371594 0.00255632 0.00133314 0.00133895]]
Document
CHYPRCE098_0402_111300_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[2.5378275e-03 9.9427360e-01 7.4278202e-04 1.1233940e-03 1.3224011e-03]]
Document
CHYPRCE098_0402_111300_300C_FB_1


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[8.0163474e-04 1.1592577e-03 9.2699908e-04 9.9633336e-01 7.7870989e-04]]
Receipt
LMEPRLE038_0308_103414_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.3153695e-04 1.1542093e-03 1.3624120e-03 9.9559349e-01 9.5832889e-04]]
Receipt
LMEPRLE038_0308_103537_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.1013184e-04 1.1424128e-03 1.7764728e-03 9.9525023e-01 9.2070218e-04]]
Receipt
LMEPRLE038_0308_103640_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.2973876e-03 6.9758779e-04 1.5334532e-03 9.9593532e-01 5.3615728e-04]]
Receipt
LMEPRLE038_0308_103721_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.1036642e-04 9.7403571e-04 1.4741484e-03 9.9561161e-01 1.0298213e-03]]
Receipt
LMEPRLE038_0308_104159_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[7.4639753e-04 1.2951008e-03 1.3248608e-03 9.9587268e-01 7.6103897e-04]]
Receipt
LMEPRLE038_0308_104316_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.2267696e-03 1.2713145e-03 1.3221962e-03 9.9531907e-01 8.6064549e-04]]
Receipt
LMEPRLE038_0308_104406_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[5.9704535e-04 7.7638560e-04 1.0008278e-03 9.9663228e-01 9.9343562e-04]]
Receipt
LMEPRLE038_0308_104501_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[8.2645495e-04 1.2286624e-03 2.5803128e-03 9.9426657e-01 1.0980925e-03]]
Receipt
LMEPRLE038_0308_104545_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00136184 0.00138279 0.00172465 0.9942259  0.0013048 ]]
Receipt
LMEPRLE038_0308_104624_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9645621e-01 9.4322913e-04 8.0488838e-04 9.5392636e-04 8.4173580e-04]]
Card
LMEPRLE038_0308_105042_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[6.2140799e-04 1.2762228e-03 9.7255368e-04 9.9636614e-01 7.6360273e-04]]
Receipt
LMEPRLE038_0308_105133_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.33363265 0.07322004 0.56362283 0.0215312  0.0079933 ]]
Mixed
LMEPRLE038_0308_105530_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9927126  0.00215215 0.00223524 0.00131618 0.00158385]]
Card
LMEPRLE038_0308_105707_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[4.7969590e-03 1.2715309e-03 9.2079211e-04 9.9216312e-01 8.4754726e-04]]
Receipt
LMEPRLE038_0308_105838_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9512094e-01 8.5860683e-04 1.4907836e-03 1.3757409e-03 1.1539019e-03]]
Card
LMEPRLE038_0308_110225_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9947726  0.0010749  0.0016396  0.00148049 0.00103243]]
Card
LMEPRLE038_0308_110346_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9749571e-01 7.0147257e-04 6.9596950e-04 5.5834465e-04 5.4838823e-04]]
Card
LMEPRLE038_0308_110451_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9954159  0.00115686 0.00116194 0.00101754 0.00124778]]
Card
LMEPRLE038_0308_110728_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9464935e-01 1.8438492e-03 1.0482061e-03 9.2669210e-04 1.5319451e-03]]
Card
LMEPRLE038_0308_110813_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9561054e-01 9.1312872e-04 1.0789217e-03 1.2786569e-03 1.1187689e-03]]
Card
LMEPRLE038_0308_110900_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9938805  0.00140451 0.0022167  0.00132654 0.00117174]]
Card
LMEPRLE038_0308_111112_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9919269  0.0020089  0.00148082 0.00271119 0.00187223]]
Card
LMEPRLE038_0308_111234_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99487007 0.00109972 0.00176527 0.00113785 0.00112721]]
Card
LMEPRLE038_0308_111321_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9677390e-01 6.7500462e-04 7.0820475e-04 1.0160326e-03 8.2688458e-04]]
Card
LMEPRLE038_0308_111416_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[9.9606448e-01 9.6938864e-04 8.3478540e-04 1.2909747e-03 8.4043056e-04]]
Card
LMEPRLE038_0308_111521_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99076617 0.00243745 0.00285935 0.00171429 0.00222264]]
Card
LMEPRLE038_0308_111621_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[9.9597025e-01 9.4083085e-04 1.2089300e-03 8.4746472e-04 1.0325843e-03]]
Card
LMEPRLE038_0308_111703_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99462503 0.00138599 0.00152773 0.00124933 0.00121184]]
Card
LMEPRLE038_0308_111754_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9680626e-01 6.3023769e-04 1.1014189e-03 6.1692478e-04 8.4521668e-04]]
Card
LMEPRLE038_0308_111834_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9920283  0.00126481 0.00421465 0.00134208 0.00115024]]
Card
LMEPRLE038_0308_111927_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9505037e-01 1.6741664e-03 1.1603095e-03 1.1357936e-03 9.7933714e-04]]
Card
LMEPRLE038_0308_112021_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9687982e-01 7.4581680e-04 7.0285361e-04 1.0701345e-03 6.0140959e-04]]
Card
LMEPRLE038_0308_112146_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9637836e-01 9.3431893e-04 1.0806042e-03 1.0064172e-03 6.0025090e-04]]
Card
LMEPRLE038_0308_112226_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9633324e-01 1.0642715e-03 6.9622131e-04 1.2281368e-03 6.7805237e-04]]
Card
LMEPRLE038_0308_112336_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[5.2719996e-03 9.4313954e-04 1.4204883e-03 9.9108630e-01 1.2780494e-03]]
Receipt
LMEPRLE038_0308_112449_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[8.7168394e-04 9.5103309e-04 1.3731278e-03 9.9587375e-01 9.3036692e-04]]
Receipt
LMEPRLE038_0308_112536_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00391286 0.00120955 0.00164114 0.9920453  0.0011911 ]]
Receipt
LMEPRLE038_0308_112640_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99005324 0.00167068 0.00444185 0.0021146  0.00171968]]
Card
LMEPRLE038_0308_112726_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[5.9592710e-03 9.6010457e-04 1.1637126e-03 9.9109143e-01 8.2547514e-04]]
Receipt
LMEPRLE038_0308_112804_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.5996062e-03 1.0323044e-03 9.9129579e-04 9.9539727e-01 9.7942678e-04]]
Receipt
LMEPRLE038_0308_112844_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9953472  0.00110816 0.00119897 0.00129289 0.00105266]]
Card
LMEPRLE038_0308_112956_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9806422e-01 3.0297108e-04 5.4538663e-04 6.0207845e-04 4.8533865e-04]]
Card
LMEPRLE038_0308_113049_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9605680e-01 7.5897394e-04 1.2335369e-03 1.0425815e-03 9.0812601e-04]]
Card
LMEPRLE038_0308_113155_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9884926  0.00268736 0.00231123 0.00192714 0.00458169]]
Card
LMEPRLE038_0308_113246_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.6322907e-03 1.0126443e-03 9.5006422e-04 9.9540436e-01 1.0005933e-03]]
Receipt
LMEPRLE038_0308_113424_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.0034136  0.00123948 0.00142309 0.9923822  0.00154165]]
Receipt
LMEPRLE038_0308_113506_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[7.5991277e-04 1.4407214e-03 2.6283117e-03 9.9443442e-01 7.3667284e-04]]
Receipt
LMEPRLE038_0308_113603_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9601257e-01 7.4505643e-04 1.2436557e-03 1.1963736e-03 8.0236042e-04]]
Card
LMEPRLE038_0308_113645_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[9.9611485e-01 9.3527295e-04 1.1754803e-03 9.5781399e-04 8.1663992e-04]]
Card
LMEPRLE038_0308_113724_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[0.00342964 0.00158486 0.00374476 0.9892681  0.00197263]]
Receipt
LMEPRLE038_0308_113805_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.004129   0.0022288  0.0019833  0.9900267  0.00163216]]
Receipt
LMEPRLE038_0308_113913_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9684900e-01 5.5132341e-04 9.4358384e-04 9.6288830e-04 6.9330604e-04]]
Card
LMEPRLE038_0308_113953_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9550855e-01 1.0830174e-03 1.2771683e-03 1.2763287e-03 8.5490424e-04]]
Card
LMEPRLE038_0308_114037_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00288403 0.00104484 0.00120864 0.9929848  0.00187777]]
Receipt
LMEPRLE038_0308_114154_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9718082e-01 3.0883576e-04 5.6431961e-04 1.2345210e-03 7.1158505e-04]]
Card
LMEPRLE038_0308_114227_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00142895 0.00136627 0.00193669 0.99407095 0.00119722]]
Receipt
LMEPRLE038_0308_114310_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[8.0389611e-04 1.1958802e-03 1.2349670e-03 9.9554437e-01 1.2208243e-03]]
Receipt
LMEPRLE038_0308_114342_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00417819 0.00168894 0.0026171  0.990153   0.00136278]]
Receipt
LMEPRLE038_0308_114424_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9743503e-01 4.9450644e-04 6.8521028e-04 7.3395879e-04 6.5121963e-04]]
Card
LMEPRLE038_0308_114458_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.01464337 0.00377019 0.00534701 0.9741703  0.00206909]]
Receipt
LMEPRLE038_0308_114547_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99452436 0.00121519 0.0016606  0.00156985 0.00102997]]
Card
LMEPRLE038_0308_114628_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9582303e-01 9.6112845e-04 1.5146673e-03 9.0555992e-04 7.9557748e-04]]
Card
LMEPRLE038_0308_114747_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.97136974 0.00229864 0.00421052 0.01868455 0.00343666]]
Card
LMEPRLE038_0308_114822_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[4.7976279e-04 7.1935507e-04 6.2514620e-04 9.9735069e-01 8.2509732e-04]]
Receipt
LMEPRLE038_0308_114912_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9569291e-01 9.8953920e-04 1.1869556e-03 1.0266899e-03 1.1039149e-03]]
Card
LMEPRLE038_0308_114950_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[7.9239398e-04 9.2018780e-04 9.8051527e-04 9.9645066e-01 8.5614674e-04]]
Receipt
LMEPRLE038_0308_115041_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[5.6487793e-04 7.4833678e-04 8.1392936e-04 9.9730009e-01 5.7280110e-04]]
Receipt
LMEPRLE038_0308_115146_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99438465 0.00116352 0.0015315  0.00167221 0.00124812]]
Card
LMEPRLE038_0308_115318_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[7.9317886e-04 9.6100633e-04 1.0113107e-03 9.9635857e-01 8.7587279e-04]]
Receipt
LMEPRLE038_0308_115410_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[5.6548312e-04 8.9578726e-04 1.2729107e-03 9.9654263e-01 7.2318577e-04]]
Receipt
LMEPRLE038_0308_115529_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9588603e-01 5.4497988e-04 1.1228238e-03 1.3430871e-03 1.1029735e-03]]
Card
LMEPRLE038_0308_115621_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9615967e-01 8.7903434e-04 9.1595080e-04 1.1246140e-03 9.2067028e-04]]
Card
LMEPRLE038_0308_115812_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9451339e-01 9.8245603e-04 1.6418768e-03 1.5136602e-03 1.3486668e-03]]
Card
LMEPRLE038_0308_115954_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.93830615 0.00673779 0.00470136 0.0391441  0.0111106 ]]
Card
LMEPRLE038_0308_120048_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.0742974e-03 8.1031496e-04 1.3914525e-03 9.9588698e-01 8.3701796e-04]]
Receipt
LMEPRLE038_0308_120131_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.970797e-01 6.966761e-04 8.261379e-04 9.359593e-04 4.615000e-04]]
Card
LMEPRLE038_0308_120304_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9600178e-01 8.6076942e-04 1.2697526e-03 9.6294336e-04 9.0470986e-04]]
Card
LMEPRLE038_0308_120353_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.6364649  0.00590098 0.00358537 0.34663275 0.00741602]]
Mixed
LMEPRLE038_0308_120428_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9935308  0.00113566 0.00207219 0.00194463 0.00131664]]
Card
LMEPRLE038_0308_120514_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9472259  0.00419628 0.00633719 0.035875   0.00636569]]
Card
LMEPRLE038_0308_120548_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.60271204 0.01039324 0.00979386 0.3640073  0.01309356]]
Mixed
LMEPRLE038_0308_120633_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9482983e-01 8.3458435e-04 1.0895138e-03 1.8539538e-03 1.3921565e-03]]
Card
LMEPRLE038_0308_120709_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.3767815  0.01115469 0.0077155  0.60021585 0.00413243]]
Mixed
LMEPRLE038_0308_120802_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[2.7742072e-03 8.4991573e-04 7.9082459e-04 9.9470335e-01 8.8166638e-04]]
Receipt
LMEPRLE038_0308_120841_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9774760e-01 4.6865232e-04 4.3749801e-04 6.4285577e-04 7.0346979e-04]]
Card
LMEPRLE038_0308_120950_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.04331106 0.00173471 0.00147171 0.95221084 0.00127171]]
Receipt
LMEPRLE038_0308_121042_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.13830712 0.00419315 0.03494343 0.78113765 0.04141868]]
Mixed
LMEPRLE038_0308_121128_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9696034e-01 7.6473865e-04 5.6644465e-04 8.8844408e-04 8.2000630e-04]]
Card
LMEPRLE038_0308_121211_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9666780e-01 1.1404789e-03 5.5010855e-04 8.6543983e-04 7.7614823e-04]]
Card
LMEPRLE038_0308_121313_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9669755e-01 7.9748448e-04 5.1343080e-04 1.3542467e-03 6.3727592e-04]]
Card
LMEPRLE038_0308_121540_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.0194257e-02 1.3943953e-03 9.4048324e-04 9.8653352e-01 9.3733583e-04]]
Receipt
LMEPRLE038_0308_122037_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[8.7402901e-04 1.1514490e-03 1.0256806e-03 9.9618077e-01 7.6813035e-04]]
Receipt
LMEPRLE038_0308_122109_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9562824e-01 9.1505458e-04 1.0463154e-03 1.1729258e-03 1.2373924e-03]]
Card
LMEPRLE038_0308_122147_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9662697e-01 1.0677505e-03 7.8129623e-04 8.5161661e-04 6.7239610e-04]]
Card
LMEPRLE038_0308_122221_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9884349  0.00250158 0.0053851  0.00210312 0.00157528]]
Card
LMEPRLE038_0308_122320_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[2.0460477e-03 8.6481683e-04 9.6604903e-04 9.9484825e-01 1.2748748e-03]]
Receipt
LMEPRLE038_0308_122354_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.98852575 0.00325299 0.00141534 0.0050033  0.00180252]]
Card
LMEPRLE038_0308_122431_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9498570e-01 1.0368404e-03 1.7532350e-03 1.2831897e-03 9.4106951e-04]]
Card
LMEPRLE038_0308_122502_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9650735e-01 8.4348343e-04 9.5128384e-04 9.5466699e-04 7.4310979e-04]]
Card
LMEPRLE038_0308_122537_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.97790146 0.0031652  0.00393077 0.01074217 0.00426036]]
Card
LMEPRLE038_0308_122651_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99338865 0.00162808 0.00151772 0.00185542 0.00161018]]
Card
LMEPRLE038_0308_122728_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.1061950e-03 1.1329348e-03 8.7380846e-04 9.9591511e-01 9.7194285e-04]]
Receipt
LMEPRLE038_0308_122804_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9867547  0.00231309 0.00108384 0.00675095 0.00309743]]
Card
LMEPRLE038_0308_122851_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[4.7009753e-04 6.1429216e-04 1.2544175e-03 9.9709320e-01 5.6804059e-04]]
Receipt
LMEPRLE038_0308_122930_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9645245e-01 8.0146530e-04 1.3831093e-03 6.9055252e-04 6.7227799e-04]]
Card
LMEPRLE038_0308_123008_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9514502e-01 1.4007660e-03 1.3664628e-03 1.1576421e-03 9.3002582e-04]]
Card
LMEPRLE038_0308_123040_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[7.4877549e-04 1.0981469e-03 1.0287291e-03 9.9601221e-01 1.1121564e-03]]
Receipt
LMEPRLE038_0308_123117_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9488008e-01 8.2557969e-04 1.9763468e-03 1.2931107e-03 1.0249706e-03]]
Card
LMEPRLE038_0308_123200_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[7.6253549e-04 9.7594620e-04 1.1216073e-03 9.9582314e-01 1.3168367e-03]]
Receipt
LMEPRLE038_0308_123243_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9210113e-01 7.8905257e-04 1.0952695e-03 3.8900417e-03 2.1244050e-03]]
Card
LMEPRLE038_0308_123325_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9556500e-01 9.4955711e-04 1.4044752e-03 1.1507302e-03 9.3024480e-04]]
Card
LMEPRLE038_0308_123407_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9648678e-01 7.2202337e-04 9.9904102e-04 9.6316973e-04 8.2906627e-04]]
Card
LMEPRLE038_0308_123450_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9482995e-01 1.2551021e-03 1.9068827e-03 1.0711163e-03 9.3701214e-04]]
Card
LMEPRLE038_0308_123533_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9940031  0.00126102 0.00187295 0.00142356 0.0014393 ]]
Card
LMEPRLE038_0308_123611_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9940758  0.00142222 0.00168045 0.00150614 0.00131536]]
Card
LMEPRLE038_0308_123651_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.98513144 0.00259518 0.00240302 0.00764784 0.00222252]]
Card
LMEPRLE038_0308_123735_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9758136e-01 5.6994974e-04 7.4106775e-04 6.8376522e-04 4.2379677e-04]]
Card
LMEPRLE038_0308_123824_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.01348804 0.00141822 0.00257513 0.9795829  0.00293569]]
Receipt
LMEPRLE038_0308_123856_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.92336696 0.00836569 0.00881566 0.04861532 0.01083634]]
Card
LMEPRLE038_0308_123933_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9015021e-01 1.3266042e-03 8.9116610e-04 5.1626498e-03 2.4694114e-03]]
Card
LMEPRLE038_0308_124011_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.00218052 0.00124172 0.00205771 0.9927631  0.00175699]]
Receipt
LMEPRLE038_0308_124046_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9694425e-01 3.4515871e-04 9.4844459e-04 1.1940276e-03 5.6813209e-04]]
Card
LMEPRLE038_0308_124122_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99409926 0.00115865 0.00183075 0.00162879 0.00128243]]
Card
LMEPRLE038_0308_124205_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9944647  0.0013697  0.00140476 0.00136022 0.00140057]]
Card
LMEPRLE038_0308_124306_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9582952e-01 7.0930825e-04 1.3665286e-03 1.1789923e-03 9.1560098e-04]]
Card
LMEPRLE038_0308_124354_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[7.8875525e-04 1.1095284e-03 9.4197510e-04 9.9654168e-01 6.1803550e-04]]
Receipt
LMEPRLE038_0308_124434_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.99284655 0.00164524 0.00231289 0.00175672 0.00143865]]
Card
LMEPRLE038_0308_124508_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9781454e-01 4.5679897e-04 6.5375521e-04 7.1888906e-04 3.5603001e-04]]
Card
LMEPRLE038_0308_124541_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9920334  0.00243809 0.0017248  0.00207413 0.00172955]]
Card
LMEPRLE038_0308_124625_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.01142783 0.00243501 0.00189465 0.98253965 0.00170297]]
Receipt
LMEPRLE038_0308_124701_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[1.0995326e-03 9.8813651e-04 1.4655641e-03 9.9520689e-01 1.2398744e-03]]
Receipt
LMEPRLE038_0308_124739_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[0.9647715  0.00193071 0.00327109 0.02760974 0.0024169 ]]
Card
LMEPRLE038_0308_124819_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[9.9487692e-01 1.2791551e-03 1.8401003e-03 1.1969502e-03 8.0699648e-04]]
Card
LMEPRLE038_0308_124854_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[7.0177618e-04 1.1151481e-03 1.0365458e-03 9.9592471e-01 1.2218341e-03]]
Receipt
LMEPRLE038_0308_124927_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.9933308  0.0018766  0.00203729 0.00140043 0.00135492]]
Card
LMEPRLE038_0308_125005_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9644047e-01 1.0558860e-03 8.7400345e-04 1.0445867e-03 5.8504986e-04]]
Card
LMEPRLE038_0308_125043_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[8.9510006e-04 8.8547962e-04 1.1620921e-03 9.9620938e-01 8.4801990e-04]]
Receipt
LMEPRLE038_0308_125120_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9675351e-01 6.1599613e-04 9.5773645e-04 9.9508709e-04 6.7769666e-04]]
Card
LMEPRLE038_0308_125153_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[9.9479938e-01 1.1558901e-03 1.9919528e-03 1.1954503e-03 8.5726025e-04]]
Card
LMEPRLE038_0308_125234_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[0.04775172 0.00233367 0.00566769 0.9420343  0.00221258]]
Receipt
LMEPRLE038_0308_125306_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.33222243 0.00790813 0.01763043 0.6258925  0.01634653]]
Mixed
LMEPRLE038_0308_125450_300C_FB_0


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
[[9.9708575e-01 7.0096727e-04 9.1784343e-04 6.5546163e-04 6.3992228e-04]]
Card
LMEPRLE038_0308_125537_300C_FB_0


In [1]:
import pandas as pd
from sklearn.metrics import classification_report
df = pd.read_csv('C:\\Users\\ChNa395\\python\\outputlist_modified.csv')

# Generate classification report
report = classification_report(df['Label'], df['predicted_label'])

print("Classification Report:")
print(report)

Classification Report:
              precision    recall  f1-score   support

        Card       0.00      0.00      0.00         6
    Document       0.05      0.02      0.03       116
       Mixed       0.09      0.01      0.02       226
       Photo       0.00      0.00      0.00       164
     Receipt       0.00      0.00      0.00        44

    accuracy                           0.01       556
   macro avg       0.03      0.01      0.01       556
weighted avg       0.05      0.01      0.01       556



In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

df = pd.read_csv('C:\\Users\\ChNa395\\python\\outputlist_modified.csv')

true_labels = df['labelInt']
predicted_labels = df['predicted_label_int']

conf_matrix = confusion_matrix(df['labelInt'], df['predicted_label_int'])
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
print(f"Accuracy: {accuracy * 100:.2f}%")
Label = ['Card', 'Document', 'Mixed', 'Photo', 'Mixed']


conf_matrix_percentage = conf_matrix / conf_matrix.sum(axis=1)[:, np.newaxis] * 100

plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix_percentage, annot=True, fmt='.2f', cmap='Blues', xticklabels=Label, yticklabels=Label)
plt.xlabel('Predicted Labels')
plt.ylabel('Labels')
plt.title('Confusion Matrix (Percentage)')
plt.show()


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
from tensorflow.keras.callbacks import TensorBoard
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit
from datetime import datetime
import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt

import os

os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

def plot_learning_curves(history):

    train_loss = history.history['loss']
    val_loss = history.history['val_loss']

    # Extract training and validation accuracy
    train_acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']

    # Plot training and validation loss
    plt.figure(figsize=(10, 5))
    plt.subplot(1, 2, 1)
    plt.plot(range(1, len(train_loss) + 1), train_loss, label='Training Loss')
    plt.plot(range(1, len(val_loss) + 1), val_loss, label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.title('Training and Validation Loss')
    plt.legend()
    
    # Plot training and validation accuracy
    plt.subplot(1, 2, 2)
    plt.plot(range(1, len(train_acc) + 1), train_acc, label='Training Accuracy')
    plt.plot(range(1, len(val_acc) + 1), val_acc, label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.title('Training and Validation Accuracy')
    plt.legend()
    
    # Show plot
    plt.tight_layout()
    plt.show()

def load_and_preprocess_image(image_path):
    # print(image_path, "Process")
    img = cv2.imread(image_path)
    img = cv2.resize(img, (448, 448))
    img = img / 255.0
    return img

def load_and_preprocess_images_from_csv(csv_file, input_dir):
    df = pd.read_csv(csv_file)
    images = []
    labels = []
    for _, row in df.iterrows():
        image_path = os.path.join(f"{input_dir}", row['Filename'].strip() + '.png')
        # print(image_path) 
        img = load_and_preprocess_image(image_path)
        # if img is None:
        #     print(f'Failed to load image from {image_path}')
        #     continue
        images.append(img)
        labels.append(row['Label'])
    return train_test_split(np.array(images), np.array(labels), test_size=0.3, random_state=42)

csvFile = "C:\\Users\\ChNa395\\python\\DeskewedCsv.csv"
input_dir = "C:\\Users\\ChNa395\\python\\BatchRun\\Dump\\AllTargetsDump\\DeskewedTargets"
x_train, x_test, y_train, y_test = load_and_preprocess_images_from_csv(csvFile, input_dir)

# x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

# Splitting the training set further into training and validation sets
for train_index, val_index in sss.split(x_train, y_train):
    X_train_final, X_val = x_train[train_index], x_train[val_index]
    y_train_final, y_val = y_train[train_index], y_train[val_index]

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_val = encoder.transform(y_val)

y_train = to_categorical(y_train)
y_val = to_categorical(y_val)

# log_dir = "C:\\Users\\ChNa395\\python\\DATA\\logsDir" + datetime.now().strftime("%Y%m%d-%H%M%S")
# tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)


model = load_model('C:\\Users\\ChNa395\\Downloads\\doc_classification\\doc_classification_modified.keras')



# Freezing the CNN layers (assuming they are the initial layers)
for layer in model.layers[:-2]: 
    layer.trainable = False

# Making sure the FCN layers are trainable
train_labels = {'Document': 0, 'Receipt': 1, 'Card': 2, 'Photo': 3, 'Unknown': 4}
val_labels = {'Document': 0, 'Receipt': 1, 'Card': 2, 'Photo': 3, 'Unknown': 4}
for layer in model.layers[-2:]:  
    layer.trainable = True

# Compile the model with a suitable optimizer and loss function
model.compile(optimizer='adam',  
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

# Model summary to verify trainable status
# model.summary()

# Train the model with your data
history = model.fit(x_train, y_train, validation_data=(X_val, y_val), epochs=10, batch_size=32)
plot_learning_curves(history)
model.save("C:\\Users\\ChNa395\\Downloads\\doc_classification\\doc_classification_modified_trained.keras")

In [ ]:
encoder = LabelEncoder()
y_test = encoder.fit_transform(y_test)
y_test = to_categorical(y_test)
print(model.evaluate(x_test, y_test))

In [ ]:
from sklearn.metrics import roc_curve, auc
import numpy as np
import matplotlib.pyplot as plt

# Make predictions on the test data
y_pred = model.predict(x_test)

# Compute ROC curve and ROC area for each class
fpr = dict()
tpr = dict()
roc_auc = dict()
n_classes = 5
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test_encoded[:, i], y_pred[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])


# First aggregate all false positive rates
all_fpr = np.unique(np.concatenate([fpr[i] for i in range(n_classes)]))

# Then interpolate all ROC curves at these points
mean_tpr = np.zeros_like(all_fpr)
for i in range(n_classes):
    mean_tpr += np.interp(all_fpr, fpr[i], tpr[i])

# Finally average it and compute AUC
mean_tpr /= n_classes



# Plot ROC curve
plt.figure(figsize=(8, 5))
for i in range(n_classes):
    plt.plot(fpr[i], tpr[i], label=f'class {i} ROC curve (AUC = {roc_auc[i]:0.2f})')


plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for Multi-class Classification')
plt.legend(loc='lower right')
plt.show()


In [ ]:
# encoder = LabelEncoder()
# y_test = encoder.fit_transform(y_test)
# y_test = to_categorical(y_test)
# print(model.evaluate(x_test, y_test))


import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit
from datetime import datetime
import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt
import imgaug.augmenters as iaa
import os

os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

def plot_learning_curves(history):
    train_loss = history.history['loss']
    val_loss = history.history['val_loss']
    train_acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']

    plt.figure(figsize=(10, 5))
    plt.subplot(1, 2, 1)
    plt.plot(range(1, len(train_loss) + 1), train_loss, label='Training Loss')
    plt.plot(range(1, len(val_loss) + 1), val_loss, label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.title('Training and Validation Loss')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(range(1, len(train_acc) + 1), train_acc, label='Training Accuracy')
    plt.plot(range(1, len(val_acc) + 1), val_acc, label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.title('Training and Validation Accuracy')
    plt.legend()

    plt.tight_layout()
    plt.show()

def load_and_preprocess_image(image_path):
    img = cv2.imread(image_path)
    img = cv2.resize(img, (448, 448))
    img = img / 255.0
    return img

def load_and_preprocess_images_from_csv(csv_file, input_dir):
    df = pd.read_csv(csv_file)
    images = []
    labels = []
    for _, row in df.iterrows():
        image_path = os.path.join(input_dir, row['Filename'].strip() + '.png')
        img = load_and_preprocess_image(image_path)
        images.append(img)
        labels.append(row['Label'])
    return train_test_split(np.array(images), np.array(labels), test_size=0.3, random_state=42)

csvFile = "C:\\Users\\ChNa395\\python\\DeskewedCsv.csv"
input_dir = "C:\\Users\\ChNa395\\python\\BatchRun\\Dump\\AllTargetsDump\\DeskewedTargets"
x_train, x_test, y_train, y_test = load_and_preprocess_images_from_csv(csvFile, input_dir)

sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, val_index in sss.split(x_train, y_train):
    X_train_final, X_val = x_train[train_index], x_train[val_index]
    y_train_final, y_val = y_train[train_index], y_train[val_index]

# Augmentation
seq = iaa.Sequential([
    iaa.Rotate((5, 5)),
    iaa.ChannelShuffle(1.0),
    iaa.Flipud(1.0)
])

def augment_images(images, labels, augmenter):
    augmented_images = augmenter(images=images)
    return np.array(augmented_images), labels

X_train_aug, y_train_aug = augment_images(X_train_final, y_train_final, seq)
X_val_aug, y_val_aug = augment_images(X_val, y_val, seq)

encoder = LabelEncoder()
y_train_aug = encoder.fit_transform(y_train_aug)
y_val_aug = encoder.transform(y_val_aug)
y_test_encoded = encoder.transform(y_test)

y_train_aug = to_categorical(y_train_aug)
y_val_aug = to_categorical(y_val_aug)
y_test_encoded = to_categorical(y_test_encoded)

model = load_model('C:\\Users\\ChNa395\\Downloads\\doc_classification\\doc_classification_modified_trained.keras')

for layer in model.layers[:-2]: 
    layer.trainable = False

for layer in model.layers[-2:]:  
    layer.trainable = True

model.compile(optimizer='adam',  
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

history = model.fit(X_train_aug, y_train_aug, validation_data=(X_val_aug, y_val_aug), epochs=10, batch_size=32)
plot_learning_curves(history)

print(model.evaluate(x_test, y_test_encoded))


In [ ]:
model.summary()

In [ ]:
from sklearn.metrics import classification_report

# Predict classes
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# Convert one-hot encoded y_test_encoded to class labels
y_test_classes = np.argmax(y_test_encoded, axis=1)

# Create a mapping of class labels
class_names = ['Card', 'Document', 'Photo', 'Receipt', 'Mixed']

# Generate classification report
report = classification_report(y_test_classes, y_pred_classes, target_names=class_names, zero_division = 1)

print(report)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
import seaborn as sns


# Predict classes
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# Convert one-hot encoded y_test_encoded to class labels
y_test_classes = np.argmax(y_test_encoded, axis=1)

# Generate confusion matrix
cm = confusion_matrix(y_test_classes, y_pred_classes)

# Convert to percentages
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
accuracy = accuracy_score(y_test_classes, y_pred_classes)

print(f"Accuracy: {accuracy * 100:.2f}%")
# Create a mapping of class labels
class_names = ['Card', 'Document', 'Photo', 'Receipt', 'Mixed']

# Plot confusion matrix
plt.figure(figsize=(10, 10))
sns.heatmap(cm, annot=True, fmt=".2%", cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.ylabel('True label')
plt.xlabel('Predicted label')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import label_binarize
from sklearn.metrics import precision_recall_curve, average_precision_score
from tensorflow.keras.models import load_model

# Load the model
model = load_model('C:\\Users\\ChNa395\\Downloads\\doc_classification\\doc_classification_modified_trained.keras')

# Preprocess y_test (ensure y_test is encoded in one-hot format)
encoder = LabelEncoder()
y_test_encoded = np.argmax(y_test, axis=1)
# y_test_encoded = encoder.fit_transform(y_test)
y_test_encoded = to_categorical(y_test_encoded)

# Predict on the test data
y_pred = model.predict(x_test)

# Initialize dictionaries to store precision, recall, and average precision for each class
precision = dict()
recall = dict()
average_precision = dict()

# Calculate precision-recall curve and average precision for each class
for i in range(5):
    precision[i], recall[i], _ = precision_recall_curve(y_test_encoded[:, i], y_pred[:, i])
    average_precision[i] = average_precision_score(y_test_encoded[:, i], y_pred[:, i])
class_names = ['Card', 'Document', 'Photo', 'Receipt', 'Mixed']
# Plot the precision-recall curve for each class
plt.figure(figsize=(8, 5))
for i in range(5):
    # plt.plot(recall[i], precision[i], label='class {0} (area = {1:0.2f})'.format(i, average_precision[i]))
    plt.plot(recall[i], precision[i], label=f'{class_names[i]} (area = {average_precision[i]:0.2f})')
    
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.legend(loc='best')
plt.show()


In [ ]:
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Make predictions on the test data
y_pred = model.predict(x_test)

class_names = ['Card', 'Document', 'Photo', 'Receipt', 'Mixed']
# Calculate the ROC curve for each class
fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(5):
    fpr[i], tpr[i], _ = roc_curve(y_test_encoded[:, i], y_pred[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot ROC curve for each class
plt.figure(figsize=(8, 5))
for i in range(5):
    plt.plot(fpr[i], tpr[i], label=f'{class_names[i]} ROC curve (AUC = {roc_auc[i]:0.2f})')


plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC curve for each class')
plt.legend(loc='best')
plt.show()


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from keras_tuner import HyperModel, RandomSearch
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Flatten


# Load the existing model
model = load_model('C:\\Users\\ChNa395\\Downloads\\doc_classification\\doc_classification_modified_trained.keras')

# Freeze the CNN layers (assuming they are the initial layers)
for layer in model.layers[:-2]:
    layer.trainable = False

# Define a HyperModel by subclassing
def build(self, hp):
    # Hyperparameters to tune
    dense_units = hp.Int('units', min_value=32, max_value=512, step=32)
    dropout_rate = hp.Float('dropout', min_value=0.0, max_value=0.5, step=0.1)
    learning_rate = hp.Float('learning_rate', min_value=1e-4, max_value=1e-2, sampling='LOG')

    # Building the FCN with tuned hyperparameters
    x = self.base_model.layers[-3].output  # Assuming the last 3 layers are FCN
    x = Flatten()(x)  # Flatten the output of the base model
    x = Dense(dense_units, activation='relu')(x)
    x = Dropout(dropout_rate)(x)
    outputs = Dense(5, activation='softmax')(x)

    model = tf.keras.Model(inputs=self.base_model.input, outputs=outputs)

    # Compile the model
    model.compile(optimizer=Adam(learning_rate=learning_rate),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    return model


train_labels = {'Card': 0, 'Document': 1, 'Photo': 2, 'Receipt': 3, 'Mixed': 4}
# Define the MyHyperModel class
class MyHyperModel(HyperModel):
    def __init__(self, base_model):
        self.base_model = base_model

    def build(self, hp):
        # Hyperparameters to tune
        dense_units = hp.Int('units', min_value=32, max_value=512, step=32)
        dropout_rate = hp.Float('dropout', min_value=0.0, max_value=0.5, step=0.1)
        learning_rate = hp.Float('learning_rate', min_value=1e-4, max_value=1e-2, sampling='LOG')

        # Building the FCN with tuned hyperparameters
        x = self.base_model.layers[-5].output  # Assuming the last 3 layers are FCN
        x = Flatten()(x)  # Flatten the output of the base model
        x = Dense(dense_units, activation='relu')(x)
        x = Dropout(dropout_rate)(x)
        outputs = Dense(5, activation='softmax')(x)

        model = tf.keras.Model(inputs=self.base_model.input, outputs=outputs)

        # Compile the model
        model.compile(optimizer=Adam(learning_rate=learning_rate),
                      loss='categorical_crossentropy',
                      metrics=['accuracy'])
        return model

val_labels = {'Card': 0, 'Document': 1, 'Photo': 2, 'Receipt': 3, 'Mixed': 4}

# Instantiate the HyperModel
hypermodel = MyHyperModel(base_model=model)

# Initialize the tuner
tuner = RandomSearch(
    hypermodel,
    objective='val_accuracy',
    max_trials=10,  # Set the number of trials to run
    executions_per_trial=1,
    directory='C:\\Users\\ChNa395\\python\\DATA\\logsDir',  # Directory to store logs
    project_name='hparam_tuning'
)

# Summary of the tunable model
tuner.search_space_summary()

# Start hyperparameter search
tuner.search(X_train_aug, y_train_aug,
             epochs=10,
             validation_data=(X_val_aug, y_val_aug))

# Get the best model
best_model = tuner.get_best_models(num_models=1)[0]

# Summary of the best model
best_model.summary()